### ISSUE TITLE
The method 'findRenderObject' was called on null. Receiver: null Tried calling: findRenderObject() The relevant error-causing widget was -> ChecklistListView 

### ISSUE THREAD

**Issue by Dhananjayan-PN** [jakebonk/FlutterChecklistView#1]
This error is thrown when I move an item towards the beginning or end of the listview. I tried to fix it but couldn't find where to edit it. Please fix this issue. Here's a video to help you understand what is going wrong.

![Screen Recording 2020-06-30 at 2 19 00 PM](https://user-images.githubusercontent.com/46382245/86108116-64837980-bae0-11ea-888b-1b75a0d489b2.gif)

**Comment by jakebonk** [comment]
I wasn't able to replicate the error but I think I tracked down all the spots it could have come from and fixed it. I also fixed the little blinking issue when starting to drag. Let me know if the next version (0.1.4) fixed this! 
Thanks

**Comment by Dhananjayan-PN** [comment]
Hi Jake,
Thanks a lot for fixing it. 0.1.4 fixed it. No more blinking and no errors. Thanks!

**Comment by Dhananjayan-PN** [comment]
@jakebonk On a different note, If I were to add a white translucent overlay when I start dragging how do I do that. I noticed that it works in your example. But for some reason, that white overlay doesn't work when I use a custom widget.
I see that the ChecklistItemView class has an onStartDragItem method. Could you tell me how I can use this to achieve the above?

**Comment by jakebonk** [comment]
If I understand correctly you want to change the ChecklistItemView based on if its being dragged? If that's the case I think the simplest way would be to use OnStartDragItem and OnDropItem to update the state of you custom widget

**Comment by Dhananjayan-PN** [comment]
Oh okay. Thanks, Jake!
